### ISSUE TITLE
Bad bundle issue

### ISSUE THREAD

**Issue by vvpyshnenko** [scalecube/scalecube-js#146]
If module with service implementation has import of @scalecube/scalecube-microservice
then builded bundle for that service while loading in browser throws error: 
```
Uncaught TypeError: Cannot read property 'TYPED_ARRAY_SUPPORT' of undefined
```
Example is calendar-service in https://github.com/jivygroup/exchange-backoffice-backend/pull/31

**Comment by IdoJS** [comment]
fixed
