### ISSUE TITLE
Prevent microservices API - breaking change

### ISSUE THREAD

**Issue by IdoJS** [scalecube/scalecube-js#148]
## General description

in the early stage of developing scalecube we have used string for address & seedAddress.
we have done it for simplicity sake (it run only on browser).

after latest API change, address & seedAddress are of type Address.

we want to stay backward compatible 
but we also want to provide the users with better control on the connection configuration.

#### Design proposition

A clear and concise description of the design proposition.

- [x] Is backward compatible

- [x] Changes existing API

#### Pull Request

[Prevent microservices API - breaking change](https://github.com/scalecube/scalecube-js/pull/151)

#### Old API

Code snippet

```typescript
  /**
   * @property
   * The seedAddress is an address of another microservice container in our distributed env.
   * seedAddress is the entry point to our distributed env.
   * if seedAddress is not provided, then the microservice instance can only wait for some other microserivce instance to connect to it.
   */
  seedAddress?: Address;
  /**
   * @property
   * An address for this microservice instance
   * other microservices can use this address to connect with this microservice container.
   */
  address?: Address;
```

#### New API

Code snippet

```typescript
  /**
   * @property
   * The seedAddress is an address of another microservice container in our distributed env.
   * seedAddress is the entry point to our distributed env.
   * if seedAddress is not provided, then the microservice instance can only wait for some other microserivce instance to connect to it.
   * string should be a URI template 'pm://host:port/path'
   */
  seedAddress?: Address | string;
  /**
   * @property
   * An address for this microservice instance
   * other microservices can use this address to connect with this microservice container.
   * string should be a URI template 'pm://host:port/path'
   */
  address?: Address | string;
```

## Behavior
scalecube will provide a default Address & seedAddress.
and if it receives a value when creating a microservice instance

| value | |
| -- | -- |
| undefined | use default|
| string | 'pm://host:port/path' |

```gherkin
Given a string
When creating microservice 
And address: string or seedAddress: string
Then the string will be parsed and update the default values.
```
**default:**

|  | seedAddress browser | seedAddress nodejs | address browser | address nodejs |
| -- | -- | -- | --| --|
| host | 'defaultSeedAddressHost' | | 'defaultAddressHost'  | |
| protocol | 'pm' |  'ws' | 'pm'  | 'ws' |
| path | 'defaultSeedAddressPath' | | 'defaultAddressPath'  | |
| port | 8000 | |  8000  | |

## Test cases

- [x] need to update all tests that include address or seedAddress
- [x] need to add tests to check successful replacement of value by the user

- [x] check optional flag true
```gherkin
Given undefined as address
    And isOptional flag = true
    When validateAddress
    Then check will pass
```
- [x] check optional flag false
```gherkin
  Given undefined as address
    And isOptional flag = false
    When validateAddress
    Then check will fail
```

- [x] check invalid host
```gherkin
    Given invalid host
    | type    | value |
    | object  | {}    |
    | array   | []    |
    | null    | null  |
    | number  | 80    |
    | boolean | true  |
    When  using the host in the address
    And   validate the address
    Then  exception will occur`
```

- [x] check invalid path
```gherkin
    Given invalid path
    | type    | value |
    | object  | {}    |
    | array   | []    |
    | null    | null  |
    | number  | 80    |
    | boolean | true  |
    When  using the path in the address
    And   validate the address
    Then  exception will occur
```

- [x] check invalid port
```gherkin
Given invalid port
    | type    | value |
    | object  | {}    |
    | array   | []    |
    | null    | null  |
    | string  | '80'  |
    | boolean | true  |
    When  using the port in the address 
    And   validate the address
    Then  exception will occur
```

- [x] check invalid protocol
``` gherkin
Given invalid protocol
    | type             | value       |
    | object           | {}          |
    | array            | []          |
    | null             | null        |
    | number           | 80          |
    | boolean          | true        |
    | not valid string | 'not valid' |
    When  using the protocol in the address
    And   validate the address
    Then  exception will occur
```

- [x] convert address: Address to fullAddress: string
```gherkin
Given valid address
    When calling getFullAddress(address)
    Then fullAddress will be received
[protocol]://[hos]t:[port]/[path]
```

- [x] invalid convert to fullAddress (address not of type Address)
```gherkin
Given invalid address
    When calling getFullAddress(address)
    Then exception will be occur
```

- [x] test getAddress
```gherkin
Given a string
  When calling getAddress with the given string
  Then result will be of type Address
```
####

- [x] API has been approved

- [x] Test cases have been prepared

- [x] Discussed with Technical lead

####

- [x] Technical review

- [x] All tests are implemented 

- [x] Documentation

**Comment by sergiupadure** [comment]
Looks good
