### ISSUE TITLE
documentation v 0.1.x

### ISSUE THREAD

**Issue by katzIdo** [scalecube/scalecube-js#175]
## General description

use [slate](https://github.com/scalecube/slate) to document scalecube

```gherkin
Given scalecube project
And doc.md file in the root of the project
And buildDoc.sh script under scripts folder
And slate project
When merging the branch to develop and bumping the version
Then the buildDoc.sh script is running 
And copy the doc.md file from scalecube to slate project
And rename it to javascript.md
```

after files are overridden refresh the server.
 
provide context for scalecube and provide code

####

- [x] Discussed with Technical lead

**Comment by IdoJS** [comment]
browser:

- **motivation**:
- **basic tutorial**
  - bootstrap
- **advance tutorial**
  - web worker
  with scalecube it is easy to use web-worker in your application.
  
- ** recepies**
- **limitations**
  the data format must be of [The structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm)

**Comment by IdoJS** [comment]
server (nodejs):

motivation:

basic tutorial

bootstrap
advance tutorial
  Gateway
** recepies**

limitations

**Comment by idanilt** [comment]
Done https://scalecube.github.io/javascript-docs/#discovery
