### ISSUE TITLE
Add error message if no valid services provided

### ISSUE THREAD

**Issue by oarashi** [scalecube/scalecube-js#38]
Example:
`
const ms = Microservices
            .builder()
            .services([])
            .build();
`
`
const ms = Microservices
            .builder()
            .services({})
            .build();
`
===> `TypeError: Cannot read property 'serviceName' of undefined`

It would be better to have more informative message

**Comment by IdoJS** [comment]
Checking Service validations.
1. service object must contain meta or constructor.meta
2. meta must contains:
   serviceName : string
   methods : object
3. invalid service won't register at the serviceRegistery.services object.
```javascript
const ms = Microservices
      .builder()
      .services(invalidService)
      .build();
ms.serviceRegistery.services // {}
```
4. creating proxy with invalid service in the api will return error message
```javascript
const serviceProxy = ms.proxy()
      .api(invalidService)
      .create();
serviceProxy // 'API must have meta property'
```

**Comment by IdoJS** [comment]
@idanilt 
does serviceName must be explicit define in the meta?
```javascript
serviceName = service.constructor.name
class GreetingService {
}

vs

serviceName = service.meta.serviceName
class GreetingService {
   meta : {
      serviceName: 'GreetingService',
   }
}
```
