### ISSUE TITLE
Service create api

### ISSUE THREAD

**Issue by IdoJS** [scalecube/scalecube-js#39]
2 options to Create Service Generator Api:

options1:
```javascript
const service = new Service(‘serviceName’)
.addMethodPromise({‘method name’ : function})
.addMethodObservable({‘method name’ : Observable})
.addTransportModel();
```

 option2 : 
```javascript
const service = new Service(‘service name’)
.add(
   promiseMethod({‘method name’ : function}),
   observableMethod({‘method name’ : Observable}),
   transport()
);
```

the end result will be:
```javascript
{
identifier : ‘global service symbol identifier shared by all services’
meta : {
 value: {
   serviceName: 'serviceName',
   methods: {
     hello: {
       returnType: ‘Promise’
     },
     repeatToStream: {
       returnType: ‘Observable’
     }
   }
 }
},
hello () {…},
repeatToStream(){…}
transport : ‘transport method’
}
```

**Comment by oarashi** [comment]
@IdoJS what about:
`
const service = new Service({
  serviceName: 'serviceName',
  methods: {
    hello: {
      type: 'Promise',
      method: () => console.log('Hello')
  },
    repeatToStream: {
      type: 'Observable',
      method: () => Observable.of()
  },
}
})
`

**Comment by oarashi** [comment]
cc @idanilt

**Comment by IdoJS** [comment]
@oarashi 
i think the problem with passing whole object literal is that users might use incorrect naming and it won’t work for them
also, it will be hard to backward compatibility

**Comment by dmitriyslaym** [comment]
Visually I like Igors approach a lot. With the correct typing IDE should even help with the correct names of properties of these options. I think we should think about the best approach that we want to stick to and don't think about how easy will it be to refactor the places where the current version of scalecube is used - the app is vary young and for now we can allow it.

**Comment by IdoJS** [comment]
@dmitriyslaym 
another argument, passing whole object literal can be very long.
with dividing it to several methods we can have separate logic and might be easier to maintain

**Comment by dmitriyslaym** [comment]
@IdoJS We can create abstractions for different parts of options to make it readable

**Comment by idanilt** [comment]
done at #55
