### ISSUE TITLE
create more Routers implementation

### ISSUE THREAD

**Issue by IdoJS** [scalecube/scalecube-js#52]
## General description

Router is responsible for picking the right remoteService from a list of available services.

#### Design proposition

A clear and concise description of the design proposition.

- [x] Is backward compatible

- [x] Adds new API

#### Pull Request

[pr](https://github.com/scalecube/scalecube-js/pull/183)

## Behavior

1. Default - pick the first available service  
2. RoundRobin - pick the next service from a list of available services 

####

- [x] Discussed with Technical lead

####

- [x] Developer review

- [x] Documentation

**Comment by idanilt** [comment]
Round robin seem like enough for now
Tags weighting can be feature in that, but I wouldn't do it now

first available - do you think we still need it?
We can impl as "sticky" feature also wouldn't do it now

**Comment by IdoJS** [comment]
i'll open separate issue for "Tags weighting"
as for the default i want to add some deterministic way of picking a service (use for tests)
