### ISSUE TITLE
multiple proxies in one line

### ISSUE THREAD

**Issue by IdoJS** [scalecube/scalecube-js#83]
## General description
Scalecube should support of creating multiple proxies from the same microservice instance without duplication of code.
current behavior:
```
const ms = microservices.create(...)
const proxy1 = ms.createProxy({definition1, router?});
const proxy2 = ms.createProxy({definition2, router?});
```
wanted behavior:
```
const ms = microservices.create(...);
const proxyOptions = [{
    awaitGreetingsService:{
      serviceName: 'greetingsService',
      methods : {...}
    }
  },
  {
    awaitFarewellService:{
      serviceName: 'farewellService',
      methods : {...}
    }
  },
    defaultRouter?: Router];

// defaultRouter - fallback incase there is no router
const {awaitGreetingsService, awaitFarewellService} =ms.requestProxies(proxyOptions, defaultRouter ?: Router);

awaitGreetingsService.then(greetingsService => {
 // greetingsService is avaliable
});

awaitFarewellService.then(farewellService => {
 // farewellService is avaliable
});
```

#### Design proposition

A clear and concise description of the design proposition.

- [x] Changes the existing API

#### Pull Request

[Link]

#### Old API

Code snippet

```typescript
/**
 * Provides the functionality of a microservice container
 */
export default interface Microservice {
  /**
   * The method is used to delete a microservice and close all the subscriptions related with it
   */
  destroy(): null;
  /**
   * Creates a proxy to a method and provides extra logic when is invoked
   */
  createProxy<T = any>(proxyOptions: ProxyOptions): T;
  /**
   * Exposes serviceCall to a user (not via Proxy)
   */
  createServiceCall(options: CreateServiceCallOptions): ServiceCall;
}

/**
 * The options that are used for the creation of the proxy for the specific microservice container
 */
export default interface ProxyOptions {
  /**
   * Custom router specifies the logic of choosing the appropriate remoteService
   */
  router?: Router;
  /**
   * The metadata for a service container, that includes the name of a service and the map of methods that are
   * included in it
   */
  serviceDefinition: ServiceDefinition;
}

```

#### New API

Code snippet

```typescript
/**
 * Provides the functionality of a microservice container
 */
export default interface Microservice {
  /**
   * The method is used to delete a microservice and close all the subscriptions related with it
   */
  destroy(): null;
  /**
   * Creates a proxy to a method and provides extra logic when is invoked
   */
  createProxy<T = any>(proxyOptions: ProxyOptions): T;
  /**
   * Creates a proxy to a method and provides extra logic when is invoked
   */
  requestProxies(proxyOptions: MultipleProxyOptions, defaultRouter ?: Router): {[serviceName: string] : Promise<Proxy>};
  /**
   * Exposes serviceCall to a user (not via Proxy)
   */
  createServiceCall(options: CreateServiceCallOptions): ServiceCall;
}

/**
 * The options that are used for the creation of the proxy for the specific microservice container
 */
export default interface MultipleProxyOptions {
  /**
   * The metadata for a service container, that includes the name of a service and the map of methods that are
   * included in it
   */
  serviceDefinition: ServiceDefinition;
}

export default interface ProxyOptions {
  /**
   * Custom router specifies the logic of choosing the appropriate remoteService
   */
  router?: Router;
  /**
   * The metadata for a service container, that includes the name of a service and the map of methods that are
   * included in it
   */
  serviceDefinition: ServiceDefinition;
}
```

## Behavior
For every service with a valid definition, a proxy will be created, pretty much, in the same way, we did before.
The behavioral change is that instead of creating each proxy in a separate line,
moreover, you were unable to know if service is actually available before trying to use it.

requestProxies will return map of Promise to a proxy.

for each key in the map you will be able to invoke the Promise and it will resolve only after the microservice found the service in the registry.

if, for some reason, one of the definitions is incorrect, 
then scalecube will throw an exception and the proxies map won't be created.

#### Consideration

List of everything to consider before writing test cases:

- [x] Changes current behavior

Specify which behavior will be changed and how or provide the link to PR.

```gherkin
   Given   2 serviceDefinitions
```

| | serviceDefinitionA | serviceDefinitionB | serviceDefinitionC
| -- | -- | -- | -- |
|serviceName| greetingService | greetingService | farewellService
|method | hello : requestResponse | greet : requestResponse | bye : requestResponse

```gherkin
   When  requesting a Proxies from the microservice
   Then   a map of Promise<proxy> by proxyName will be created
```

```
{
  greetingService : Promise<Proxy<hello: requestResponse, greet: requestResponse>>,
  farewellService : Promise<Proxy<bye: requestResponse>>,
}
```

## Test cases

- A positive scenario and an example to a successful microservice creation from multiple service defitions.
``` Gherkin
Scenario: Creating multiple proxies from the same microservice instance
  Given   microservice instance with
  |service          |definition               | method                  |
  |greetingService  |greetingServiceDefinition| greet : requestResponse |
  |helloService     |helloServiceDefinition   | hello : requestResponse |
  When    creating a Proxies from the microservice
  Then    a map of Promise<proxy> by proxyName will be created
  |proxy          |method                  |
  |greetingProxy  |greet : requestResponse |
  |helloProxy     |hello : requestResponse |   
```

- In a scenario where at least one of the serviceDefiniton is invalid.
A map of Promise<proxy> will be created, 
When trying to request the invalid proxy, it will be rejected with the relevant exception.
``` Gherkin
Scenario:  creating multiple proxies and some of them with invalid serviceDefinition
   Given   2 serviceDefinitions (‘A’, ‘B’, ‘C’)
   And     B is invalid
   And    creating a Proxies from the microservice
   And    a map of Promise<proxy> by proxyName will be created
   When trying to request the invalid Proxy 
   Then     a relevant exception will be thrown for the invalid serviceDefinition(‘B’)
```

Link to the PR with test cases, that are written in _**Gherkin Syntax**_ and cover all the possible scenarios.

[Link]

## Key Performance Indicator (KPI) Definition

Improve Scalecube usage for the clients

## Ready for implementation

- [x] API has been approved 

- [x] Test cases have been prepared

## Definition of Done

- [x] Developer review

- [x] QA review

- [x] All tests are implemented 

- [x] Documentation

**Comment by idanilt** [comment]
have you consider return: `{[serviceName]: proxy}`?
instead of array

```ts
const [proxy1, proxy2] = ms.createProxy(proxyOptions, defaultRouter ?: Router);
// ==>
const { authService, configService } = ms.createProxy(proxyOptions, defaultRouter ?: Router);
```

**Comment by idanilt** [comment]
The proposal imply ProxyOptions will be without router
You need also to specify it in the API section

Support both options (configure it from options and args) seem redundant
Choose 1 one option, prefer this one `proxyOptions, defaultRouter ?: Router`
Most people use 1 serviceCall / router and many proxies and in the worse case they can write 2 lines

**Comment by IdoJS** [comment]
createProxy<T = any>(proxyOptions: ProxyOptions[], defaultRouter ?: Router): {[serviceName: string] : Proxy<T>};

**considerations**:

-  when creating a proxy with 2 serviceDefinitions that both have the same serviceName.

make sure that the methods are added and not override each other.

**Comment by RoykeeOM2** [comment]
Changed the test case with invalid serviceDefinition, also moved it to its' proper place in the description.

**Comment by vvpyshnenko** [comment]
New Api for createProxy method define proxyOptions argument as array of service definitions. It allows to pass several definitions with the same serviceName but different set of methods. For example it is usefull when we have one service with huge number of methods (MpRemoteService) and want to have proxies for specific sets of its methods (remoteAuthProxy, remoteTradeProxy). Since the return type of createProxy is Object then it is not allowed  to do this. Instead implementation should resolve the conflict by merging definitions  in some way. My suggestion is to have the same type (array or Object) for input options argument and output result.

**Comment by IdoJS** [comment]
what about just passing a map
key: proxyName
value: definition
```
const {
  remoteAuthService: AuthenticationServiceInterface,
  remoteTradeService: TradeServiceInterface
  } = ms.createProxy({
          'remoteAuthService': serviceDefinition1,
          'remoteTradeService' :'serviceDefinition2'
        },
     );
```
API
```ts
/**
 * Provides the functionality of a microservice container
 */
export default interface Microservice {
  /**
   * The method is used to delete a microservice and close all the subscriptions related with it
   */
  destroy(): null;
  /**
   * Creates a proxy to a method and provides extra logic when is invoked
   */
  createProxy<T = any>(proxyOptions: ProxyOptions, defaultRouter ?: Router): {[serviceName: string] : Proxy<T>};
  /**
   * Exposes serviceCall to a user (not via Proxy)
   */
  createServiceCall(options: CreateServiceCallOptions): ServiceCall;
}

/**
 * The options that are used for the creation of the proxy for the specific microservice container
 */
export default interface ProxyOptions {
  /**
   * The metadata for a service container, that includes the name of a service and the map of methods that are
   * included in it
   */
  [proxyName:string]: ServiceDefinition;
}
```

**Comment by IdoJS** [comment]
```ts
export default interface Microservice {
 // ... all other methods
  /**
   * Create a map of Promises to proxy.
   */
  createProxies(proxyOptions: MultipleProxyOptions, defaultRouter ?: Router): ProxiesMap | AsyncProxiesMap};
}

/**
 * The options that are used for the creation of the proxy for the specific microservice container
 */
export default interface MultipleProxyOptions {
  /**
   * The metadata for a service container, that includes the name of a service and the map of methods that are
   * included in it
   */
  [proxyName:string]: ServiceDefinition;
/**
*
*/
 isAsync: boolean
}

  /**
   * Map of generic proxyName and a Promise to the proxy
   */
interface AsyncProxiesMap {
  [proxyName: string]: Promise<any>;
}
interface ProxiesMap {
  [proxyName: string]: any;
}
```

**Comment by vvpyshnenko** [comment]
Todo validation check for duplication of proxyName

**Comment by IdoJS** [comment]
```gherkin
Given a microservice 
And 2 ProxiesOptions objects
```

|proxy| proxyName | serviceDefinition
| -- | -- | -- |
| proxy1 | 'proxyName' | greetingsServiceDefinition |
| proxy2 | 'proxyName' | greetingsServiceDefinition |

``` gherkin
When createProxies with both ProxiesOptions
Then error will be thrown
And proxiesMap won't be created
```
